In [1]:
from os.path import join
import pandas as pd
from make_dataset import make_dataset
from sklearn.metrics import mean_absolute_error

In [2]:
path = '\\Users\\ineeji\\Desktop\\새 폴더\\Ineeji\\datas\\데이터합본_파생변수 제거.csv'
train_x, train_y, test_x, test_y = make_dataset(path)

===================================
===================================
==============complete=============
===================================
===================================

In [3]:
train_x

,PIC23106(Top P),FIC23105(P/A RT Flow),A+B,TI23118(D/O Liquid T),TI23502(D/O Vapor T)
0,0.66949999999999998401,324.95240000000001145963,750.63670000000001891749,244.48810000000000286491,305.36910000000000309228
1,0.66859999999999997211,325.03019999999997935447,750.43290000000001782610,248.46530000000001336957,317.27920000000000300133
2,0.66879999999999995008,329.89789999999999281499,751.32539999999994506652,243.68600000000000704858,303.54250000000001818989
3,0.66939999999999999503,330.00940000000002783054,751.13310000000001309672,241.97440000000000281943,299.93520000000000891305
4,0.66949999999999998401,330.02480000000002746674,751.09590000000002874003,243.90270000000001004992,302.28379999999998517524
...,...,...,...,...,...
1444,0.64000000000000001332,284.94850000000002410161,737.76319999999998344720,230.31229999999999336069,301.35820000000001073204
1445,0.63990000000000002434,284.98110000000002628440,738.33400000000006002665,230.93010000000001014087,299.52719999999999345164
1446,0.63970000000000004636,285.00959999999997762643,738.90840000000002874003,228.69569999999998799467,295.12069999999999936335
1447,0.63990000000000002434,284.99200000000001864464,738.83169999999995525286,229.22300000000001318767,300.44869999999997389750
1448,0.63990000000000002434,297.23770000000001800800,738.40840000000002874003,228.84680000000000177351,299.27989999999999781721

# Modeling